# Generated by Django 4.0.6 on 2022-07-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fearfuel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='overview',
            field=models.TextField(blank=True),
        ),
    ]
